language: java

jdk: oraclejdk8
install: true
before_install:
  - chmod +x mvnw
before_script:
  - echo "Starting build"
script:
  - ./mvnw clean package
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful"
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - echo "Build was failed"
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - CaH4aZzz@gmail.com
    on_success: never
    on_failure: always
#just comment

