language: java

jdk:
  - oraclejdk8
  before_install:
    - chmod +x mvnw
install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - echo "Starting build"
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful"
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - echo "Build was failed"
cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    recipients:
      - CaH4aZzz@gmail.com
    on_success: never
    on_failure: always

